export const myPhotos = [
    '/images/photo1.jpeg',
    '/images/photo2.jpeg',
    '/images/photo3.jpeg',
    '/images/photo4.jpeg',
];

export const aboutMeContent = (
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque totam, quod doloremque incidunt illo quo nam corporis labore voluptatum? Numquam aut ea, laborum nemo voluptate explicabo nisi nam dolores a ex nostrum, quod fugit saepe at illo perspiciatis temporibus sint obcaecati, recusandae vel corrupti vitae. Eius optio officiis animi iste corporis nihil nam, praesentium voluptates reiciendis earum enim debitis cumque cum perspiciatis rerum quia accusamus, dicta eligendi alias. Aut repellendus excepturi dolorum, quae sequi numquam temporibus amet neque quasi id incidunt rerum, corporis doloremque aliquid ipsa voluptates deserunt nobis commodi odio, quisquam sed in maxime harum praesentium. Assumenda nostrum dolore soluta earum nam corporis? Odio, quasi ratione quo, a molestias laudantium nemo cupiditate eligendi voluptatibus, atque pariatur laboriosam fuga recusandae consequuntur eius sint minus optio doloribus eveniet architecto? Explicabo quaerat voluptas impedit at aut, deleniti laudantium ipsam tenetur quod officiis tempore repudiandae ducimus doloribus deserunt architecto, veniam obcaecati voluptatibus, fugit porro et accusantium pariatur? Ad quas quibusdam laudantium esse placeat quos velit. Nihil nulla commodi esse consequatur est qui tempore, nemo deserunt? Optio, itaque! Voluptatem fuga nobis quod maxime quasi quisquam tempore, iusto obcaecati, numquam accusamus recusandae est dolore ex culpa repellendus atque amet nemo. Distinctio deserunt labore soluta? Quibusdam laboriosam eveniet mollitia, iusto deserunt corporis nisi officiis adipisci praesentium, saepe eum, autem laborum error? Natus voluptatibus deserunt, omnis aliquid beatae repellat? Laboriosam illo dolores neque culpa autem. Ex quibusdam corporis ipsa nisi quae magnam odio earum voluptatum facilis, aut error velit pariatur culpa officiis ullam tempora, sit similique at aliquid modi. Cupiditate aut laboriosam deserunt architecto aliquid, accusamus natus delectus laudantium in tempora obcaecati assumenda possimus iusto excepturi unde illum aperiam quisquam distinctio, ex repellat non maiores temporibus ratione perferendis! Corrupti nulla cum labore dicta itaque, illum ducimus tenetur nostrum, alias quo aperiam, quia odio beatae dolore quaerat possimus?</p>
);